<a href="https://colab.research.google.com/github/Soumaditya777/Learning-Repo/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [3]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [13]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[5896, 5163, 8508, 9492], [5896, 5163, 8508, 4443], [5896, 3585, 8508, 4156], [8589, 9508, 5633, 5558, 7052], [8589, 9508, 5633, 5558, 734], [5637, 5896, 4404, 8508, 2284], [7985, 5847, 8495, 5558]]


### Word Embedding Represntation

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [35]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5896 5163 8508 9492]
 [   0    0    0    0 5896 5163 8508 4443]
 [   0    0    0    0 5896 3585 8508 4156]
 [   0    0    0 8589 9508 5633 5558 7052]
 [   0    0    0 8589 9508 5633 5558  734]
 [   0    0    0 5637 5896 4404 8508 2284]
 [   0    0    0    0 7985 5847 8495 5558]]


In [17]:
## 10 feature dimesnions
dim=10


In [18]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
##'the glass of milk',
embedded_docs[0]

array([   0,    0,    0,    0, 5896, 5163, 8508, 9492], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 72ms/step


array([[ 0.03938437, -0.02009605, -0.03878935, -0.04955565,  0.00419912,
        -0.01431773,  0.02523251,  0.01653036,  0.04291571, -0.00864979],
       [ 0.03938437, -0.02009605, -0.03878935, -0.04955565,  0.00419912,
        -0.01431773,  0.02523251,  0.01653036,  0.04291571, -0.00864979],
       [ 0.03938437, -0.02009605, -0.03878935, -0.04955565,  0.00419912,
        -0.01431773,  0.02523251,  0.01653036,  0.04291571, -0.00864979],
       [ 0.03938437, -0.02009605, -0.03878935, -0.04955565,  0.00419912,
        -0.01431773,  0.02523251,  0.01653036,  0.04291571, -0.00864979],
       [ 0.03059326, -0.04286614,  0.00899569,  0.00743791, -0.000781  ,
         0.04186494,  0.03977301,  0.00326709,  0.00619651, -0.01993654],
       [ 0.02512412, -0.0087087 ,  0.03144198,  0.00704668, -0.00177735,
        -0.03415867, -0.00100178,  0.01562483,  0.03178963,  0.02784893],
       [-0.00653008,  0.02340979, -0.01967902, -0.00494973, -0.02693756,
        -0.03746525,  0.01460877, -0.00449115

In [20]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 737ms/step
[[[-4.03623655e-03  3.57888825e-02 -2.73850914e-02 -2.63651256e-02
   -2.46404894e-02 -3.26929241e-02  1.57370605e-02 -3.21861506e-02
   -8.38320330e-03  1.88927092e-02]
  [-4.03623655e-03  3.57888825e-02 -2.73850914e-02 -2.63651256e-02
   -2.46404894e-02 -3.26929241e-02  1.57370605e-02 -3.21861506e-02
   -8.38320330e-03  1.88927092e-02]
  [-4.03623655e-03  3.57888825e-02 -2.73850914e-02 -2.63651256e-02
   -2.46404894e-02 -3.26929241e-02  1.57370605e-02 -3.21861506e-02
   -8.38320330e-03  1.88927092e-02]
  [-4.03623655e-03  3.57888825e-02 -2.73850914e-02 -2.63651256e-02
   -2.46404894e-02 -3.26929241e-02  1.57370605e-02 -3.21861506e-02
   -8.38320330e-03  1.88927092e-02]
  [ 4.52671535e-02  2.52691768e-02  4.91959564e-02  3.41257192e-02
   -2.71412265e-02 -3.54504362e-02 -4.62761521e-02  9.74501297e-03
    4.31476273e-02 -3.06700598e-02]
  [ 2.51817740e-02  2.27102377e-02  3.50487866e-02  1.08528733e-02
   -9.93204117e-03 -3.30973156e-02 -3.828717

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 5896, 5163, 8508, 9492], dtype=int32)

In [22]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[-0.00403624  0.03578888 -0.02738509 -0.02636513 -0.02464049 -0.03269292
   0.01573706 -0.03218615 -0.0083832   0.01889271]
 [-0.00403624  0.03578888 -0.02738509 -0.02636513 -0.02464049 -0.03269292
   0.01573706 -0.03218615 -0.0083832   0.01889271]
 [-0.00403624  0.03578888 -0.02738509 -0.02636513 -0.02464049 -0.03269292
   0.01573706 -0.03218615 -0.0083832   0.01889271]
 [-0.00403624  0.03578888 -0.02738509 -0.02636513 -0.02464049 -0.03269292
   0.01573706 -0.03218615 -0.0083832   0.01889271]
 [ 0.04526715  0.02526918  0.04919596  0.03412572 -0.02714123 -0.03545044
  -0.04627615  0.00974501  0.04314763 -0.03067006]
 [ 0.02518177  0.02271024  0.03504879  0.01085287 -0.00993204 -0.03309732
  -0.03828717 -0.00412067 -0.02138075 -0.00491695]
 [ 0.04467127  0.03948312 -0.02774115 -0.04682946  0.01638497  0.00738906
  -0.03377222  0.03564296  0.02353552 -0.01778682]
 [ 0.00025616  0.03159073  0.02001761 -0.04520646  0.02480718  0.01106805
   0.00035697

In [25]:
### Assignment

sent2=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [36]:
sent2

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [41]:
onehot_repr=[one_hot(words,voc_size)for words in sent2]
print(onehot_repr)

[[5896, 3956, 7763, 5633, 1528, 4072], [7951, 2061, 7763, 5678, 9045, 3873], [8589, 973, 2480, 8259], [5896, 604, 7763, 4122, 5896, 3000], [9056, 6872, 7918, 7763, 5678, 9045, 3873], [3218, 7763, 5678, 9045, 2170, 1171]]


In [44]:
sent2_length=8
embedded_docs2=pad_sequences(onehot_repr,padding='post',maxlen=sent2_length)
print(embedded_docs2)

[[5896 3956 7763 5633 1528 4072    0    0]
 [7951 2061 7763 5678 9045 3873    0    0]
 [8589  973 2480 8259    0    0    0    0]
 [5896  604 7763 4122 5896 3000    0    0]
 [9056 6872 7918 7763 5678 9045 3873    0]
 [3218 7763 5678 9045 2170 1171    0    0]]


In [43]:
voc_size=10000

In [45]:
dim=10

In [46]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [47]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [51]:
embedded_docs2

array([[5896, 3956, 7763, 5633, 1528, 4072,    0,    0],
       [7951, 2061, 7763, 5678, 9045, 3873,    0,    0],
       [8589,  973, 2480, 8259,    0,    0,    0,    0],
       [5896,  604, 7763, 4122, 5896, 3000,    0,    0],
       [9056, 6872, 7918, 7763, 5678, 9045, 3873,    0],
       [3218, 7763, 5678, 9045, 2170, 1171,    0,    0]], dtype=int32)